# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    ryan:
                        password: $2y$13$JfWSDs.yYD54KV5.vi/9N.ok.qJYjSmw9Dq94JSsnG0Po/Y.PoK76
                        roles: 'ROLE_USER'
                    admin:
                        password: $2y$13$em3FE1SYnWPXl3YDaLnJWORYl4gWSz8sY7nIX5D5XdV.H45kSQvTS
                        roles: 'ROLE_ADMIN'
        bdd:
            entity:
                class: AppBundle\Entity\User
                property: _email
    encoders:
          AppBundle\Entity\User: bcrypt
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: bdd
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            form_login:
                login_path: app_security_login
                check_path: app_security_login
            logout:
                path: /logout
                target: /
    access_control:
            # require ROLE_ADMIN for /admin*
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/admin, roles: ROLE_ADMIN }

